In [2]:
import pandas as pd
data = pd.read_csv('/Users/rustem/Desktop/events filters к тестовому Product Analyst Q1 2024.csv')

In [3]:
# Удаление столбца event_label
data.drop('event_label', axis=1, inplace=True)

In [5]:
data

      event_category              event_action  total_events  unique_events
0       city_landing       price_button_submit             8              7
1       city_landing       price_button_submit            12             10
2       city_landing  search-tools-button_open             2              2
3       city_landing  filters-categories_click             1              1
4       city_landing       price_button_submit             2              2
...              ...                       ...           ...            ...
19087   city_landing  search-tools-button_open            38             32
19088   city_landing  filters-categories_click             3              3
19089   city_landing  search-tools-button_open            16             16
19090   city_landing       price_button_submit             7              7
19091      City Page                Page Visit            33             25

[19092 rows x 4 columns]

In [6]:
# Удаление столбца event_category
data.drop('event_category', axis=1, inplace=True)
data

                   event_action  total_events  unique_events
0           price_button_submit             8              7
1           price_button_submit            12             10
2      search-tools-button_open             2              2
3      filters-categories_click             1              1
4           price_button_submit             2              2
...                         ...           ...            ...
19087  search-tools-button_open            38             32
19088  filters-categories_click             3              3
19089  search-tools-button_open            16             16
19090       price_button_submit             7              7
19091                Page Visit            33             25

[19092 rows x 3 columns]

In [8]:
# Сгруппировать данные по городам и суммировать метрики
grouped_data = data.groupby('event_action').agg({
    'total_events': 'sum',
    'unique_events': 'sum'
}).reset_index()

grouped_data

                event_action  total_events  unique_events
0                 Page Visit       2124993        1384478
1        clear_filter_mobile          3599           2788
2        dates_filter_mobile         13038          10272
3             end_date_click         14638          11738
4   filters-categories_click         80065          62539
5          pay-type_checkbox          7321           5465
6         price_button_close         14247          11646
7        price_button_submit         71890          63063
8                price_first          8572           6676
9               price_second          2826           1995
10               price_third           904            595
11  search-tools-button_open         94210          85773
12          start_date_click         19939          14501
13      ticket-type_checkbox         22882          17918

In [12]:
# Вопрос 3. Топ-10 разделов фильтров.Сортировка данных по столбцу unique_events в порядке убывания
top_event_action_by_unique_events = grouped_data.sort_values(by='unique_events', ascending=False)

top_event_action_by_unique_events.head(10)

                event_action  total_events  unique_events
0                 Page Visit       2124993        1384478
11  search-tools-button_open         94210          85773
7        price_button_submit         71890          63063
4   filters-categories_click         80065          62539
13      ticket-type_checkbox         22882          17918
12          start_date_click         19939          14501
3             end_date_click         14638          11738
6         price_button_close         14247          11646
2        dates_filter_mobile         13038          10272
8                price_first          8572           6676

In [14]:
# Топ-10 разделов фильтров.Сортировка данных по столбцу total_events в порядке убывания
top_event_actions_by_total_events = grouped_data.sort_values(by='total_events', ascending=False)
top_event_actions_by_total_events.head(10)

                event_action  total_events  unique_events
0                 Page Visit       2124993        1384478
11  search-tools-button_open         94210          85773
4   filters-categories_click         80065          62539
7        price_button_submit         71890          63063
13      ticket-type_checkbox         22882          17918
12          start_date_click         19939          14501
3             end_date_click         14638          11738
6         price_button_close         14247          11646
2        dates_filter_mobile         13038          10272
8                price_first          8572           6676

Ответ на 3-ий вопрос:

Самыми популярными фильтрами являются: 
    
Page Visit, 
search-tools-button_open, 
filters-categories_click, 
price_button_submit, 
icket-type_checkbox

In [22]:
# Вопрос 4. Как часто люди пользуются выбором цен? Выберем только фильтры по ценам и положим значения в список events для фильтрации
events_to_filter = ['Page Visit', 'price_first', 'price_second', 'price_third']

# Фильтрация данных
filtered_events = grouped_data[grouped_data['event_action'].isin(events_to_filter)]

# Вывод результата
print(filtered_events)

    event_action  total_events  unique_events
0     Page Visit       2124993        1384478
8    price_first          8572           6676
9   price_second          2826           1995
10   price_third           904            595

In [21]:
# Сумма total_events и unique_events для фильтров price_first, price_second, price_third
total_events_filters = filtered_events[filtered_events['event_action'].isin(['price_first', 'price_second', 'price_third'])]['total_events'].sum()
unique_events_filters = filtered_events[filtered_events['event_action'].isin(['price_first', 'price_second', 'price_third'])]['unique_events'].sum()

# Сумма total_events и unique_events для страницы Page Visit
total_events_page_visit = filtered_events[filtered_events['event_action'] == 'Page Visit']['total_events'].sum()
unique_events_page_visit = filtered_events[filtered_events['event_action'] == 'Page Visit']['unique_events'].sum()

# Доля суммы total_events и unique_events по фильтрам от общего количества для страницы Page Visit
total_events_ratio = total_events_filters / total_events_page_visit
unique_events_ratio = unique_events_filters / unique_events_page_visit

# Вывод результатов
print("Сумма общего использования фильтров цен:", total_events_filters)
print("Сумма уникальных пользователей использовавших фильтры цен:", unique_events_filters)
print("Сумма общего посещения страницы Page Visit:", total_events_page_visit)
print("Сумма уникальных пользователей посетивших страницу Page Visit:", unique_events_page_visit)
print("Доля общего количества раз использования фильтра цен от общего количества заходов на страницу:", total_events_ratio)
print("Доля уникальных пользователей, использовавших фильтры цен от общего числа уникальных пользователей зашедших на страницу:", unique_events_ratio)

Сумма общего использования фильтров цен: 12302
Сумма уникальных пользователей использовавших фильтры цен: 9266
Сумма общего посещения страницы Page Visit: 2124993
Сумма уникальных пользователей посетивших страницу Page Visit: 1384478
Доля общего количества раз использования фильтра цен от общего количества заходов на страницу: 0.0057891955408794285
Доля уникальных пользователей, использовавших фильтры цен от общего числа уникальных пользователей зашедших на страницу: 0.006692775183137616

Ответ на 4-ый вопрос: Только 1 человек из 150 уникальных пользователей пользуется фильтром по цене